version: "3"
services:
  # Server
  unicorn:
    build:
      context: "./unicorn"
      dockerfile: "dockerfile.dev"
    container_name: unicorn
    ports:
      - "5000:5000"
    volumes:
      - ./unicorn:/opt/app
    networks:
      - app-network
  # Client
  dingo:
    build:
      context: "./dingo"
      dockerfile: "dockerfile.dev"
    ports:
      - "3000:3000"
    volumes:
      - ./dingo:/opt/app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

